// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0HYq2r-67NK-yt7S18uMal2c5Yn_nwo',
    appId: '1:385285036636:web:eac4848fa4e1fbc1652499',
    messagingSenderId: '385285036636',
    projectId: 'sai-life',
    authDomain: 'sai-life.firebaseapp.com',
    storageBucket: 'sai-life.appspot.com',
    measurementId: 'G-DWQCHLTMFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJTcrJy8P-LDo8iyplWJ2E1AAJakOhiM',
    appId: '1:385285036636:android:0955daaf8667d69b652499',
    messagingSenderId: '385285036636',
    projectId: 'sai-life',
    storageBucket: 'sai-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkC1brRU3Vk-TGkG_V8o3oQRIJLlWYW8',
    appId: '1:385285036636:ios:d36cfa1d0688017c652499',
    messagingSenderId: '385285036636',
    projectId: 'sai-life',
    storageBucket: 'sai-life.appspot.com',
    iosClientId: '385285036636-ee9aji1q1fusjuqk2f05oekcakpn8449.apps.googleusercontent.com',
    iosBundleId: 'com.example.saiLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkC1brRU3Vk-TGkG_V8o3oQRIJLlWYW8',
    appId: '1:385285036636:ios:d36cfa1d0688017c652499',
    messagingSenderId: '385285036636',
    projectId: 'sai-life',
    storageBucket: 'sai-life.appspot.com',
    iosClientId: '385285036636-ee9aji1q1fusjuqk2f05oekcakpn8449.apps.googleusercontent.com',
    iosBundleId: 'com.example.saiLife',
  );
}
